import type { Metadata } from "next";
import { notFound } from "next/navigation";
import "./globals.css";
import { TypeLocales } from "@/i18n/routing";
import { hasLocale } from "@/i18n/utils";
import { Navbar } from "@/app/[locale]/_components/Navbar";
import { getLocaleData } from "@/i18n/request";
import { NextIntlClientProvider } from "next-intl";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(locale as TypeLocales)) {
    notFound();
  }
  const { messages } = await getLocaleData(locale);
  return (
    <html lang="en">
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <div className="flex flex-col min-h-screen bg-zinc-950">
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
